# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-23 19:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_kabar_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kabar',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='atestation',
            name='number',
            field=models.CharField(default=datetime.datetime(2017, 6, 23, 19, 10, 58, 782863, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
